### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by Devance02** [a597873885/webfunny_event#12]
err name: TypeError
err message: Cannot read property 'userId' of undefined
err stack: TypeError: Cannot read property 'userId' of undefined
    at register (/opt/tomcat/webFun/webfunny_event/controllers/controllers.js:1:277828)
    at async /opt/tomcat/webFun/webfunny_event/app.js:43:9
    at async /opt/tomcat/webFun/webfunny_event/middlreware/sqlCheck.js:33:9
    at async /opt/tomcat/webFun/webfunny_event/middlreware/auth.js:39:13
    at async /opt/tomcat/webFun/webfunny_event/app.js:23:9

**Comment by Devance02** [comment]
注册的时候，信息填写完毕提示没有userId
